import { useEffect, useRef, useState } from 'react';
import type * as React from 'react';
import { toPng } from 'html-to-image';
import type { DrawReaction, MatchState } from '@without-words/shared';

const COLORS = ['#eaf8ff', '#5ee7f5', '#ff796c', '#f7cf77'];
const SIZES = [3, 8, 16];
const reactions: DrawReaction[] = ['✦', '♡', '☀', '!', '?'];

export function DrawGame({ state, onSubmit, onReact, onAgain, onHome }: { state: MatchState; onSubmit: (image: string) => void; onReact: (reaction: DrawReaction) => void; onAgain: () => void; onHome: () => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null), galleryRef = useRef<HTMLDivElement>(null), history = useRef<ImageData[]>([]), drawing = useRef(false);
  const [color, setColor] = useState(COLORS[0]), [size, setSize] = useState(SIZES[1]), [remaining, setRemaining] = useState(60), [confirmSubmit, setConfirmSubmit] = useState(false);
  const revealed = state.phase === 'revealed', submitted = Boolean(state.submitted);
  useEffect(() => { const timer = window.setInterval(() => setRemaining(Math.max(0, Math.ceil(((state.drawEndsAt ?? Date.now()) - Date.now()) / 1000))), 200); return () => clearInterval(timer); }, [state.drawEndsAt]);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext('2d')!; history.current = []; ctx.fillStyle = '#07131e'; ctx.fillRect(0, 0, canvas.width, canvas.height); }, [state.topic]);
  const point = (e: React.PointerEvent<HTMLCanvasElement>) => { const c = canvasRef.current!, r = c.getBoundingClientRect(); return { x: (e.clientX - r.left) * c.width / r.width, y: (e.clientY - r.top) * c.height / r.height }; };
  const start = (e: React.PointerEvent<HTMLCanvasElement>) => { if (revealed || submitted || remaining <= 0) return; e.currentTarget.setPointerCapture(e.pointerId); const ctx = canvasRef.current!.getContext('2d')!, p = point(e); history.current.push(ctx.getImageData(0, 0, 900, 600)); ctx.beginPath(); ctx.moveTo(p.x, p.y); drawing.current = true; };
  const move = (e: React.PointerEvent<HTMLCanvasElement>) => { if (!drawing.current) return; const ctx = canvasRef.current!.getContext('2d')!, p = point(e); ctx.lineTo(p.x, p.y); ctx.strokeStyle = color; ctx.lineWidth = size; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.stroke(); };
  const end = () => { drawing.current = false; };
  const clear = () => { const c = canvasRef.current!, ctx = c.getContext('2d')!; history.current.push(ctx.getImageData(0, 0, 900, 600)); ctx.fillStyle = '#07131e'; ctx.fillRect(0, 0, c.width, c.height); };
  const undo = () => { const image = history.current.pop(); if (image) canvasRef.current!.getContext('2d')!.putImageData(image, 0, 0); };
  const submit = () => { const c = canvasRef.current; if (c && !submitted && remaining > 0) onSubmit(c.toDataURL('image/png')); setConfirmSubmit(false); };
  const own = state.drawings?.[state.role], other = state.drawings?.[state.role === 'guide' ? 'runner' : 'guide'];
  if (state.phase === 'intro') return <main className="center draw-intro"><Atmosphere/><div className="connection-line"><span/><i/><span/></div><p className="eyebrow">A shared idea is waiting</p><h1>{state.topic}</h1><p className="muted">The canvas opens together.</p><div className="countdown">{Math.max(0, Math.ceil(((state.introEndsAt ?? Date.now()) - Date.now()) / 1000)) || '·'}</div></main>;
  if (revealed) { const save = async () => { if (!galleryRef.current) return; const link = document.createElement('a'); link.download = 'same-word-two-worlds.png'; link.href = await toPng(galleryRef.current, { pixelRatio: 2 }); link.click(); }; return <main className="draw-result"><Atmosphere/><p className="eyebrow">THE SAME WORD · TWO WORLDS</p><h1>{state.topic}</h1><p className="draw-subtitle">Two strangers. One idea. No instructions.</p><div className="draw-locations"><span><b>{state.countries[0].city}</b><small>{state.countries[0].name}</small></span><strong>↕ {state.distanceKm.toLocaleString()} km<small>APPROXIMATE</small></strong><span><b>{state.countries[1].city}</b><small>{state.countries[1].name}</small></span></div><div className="draw-gallery" ref={galleryRef}>{([['YOUR WORLD', own], ['THE OTHER WORLD', other]] as const).map(([label, image]) => <figure key={label}><figcaption>{label}</figcaption><div className="revealed-image">{image ? <img src={image} alt={label} /> : <span>No drawing submitted</span>}</div></figure>)}</div><div className="reaction-panel"><p>Send one quiet reaction</p><div>{reactions.map(r => <button key={r} className={state.reactions?.[state.role] === r ? 'chosen' : ''} disabled={Boolean(state.reactions?.[state.role])} onClick={() => onReact(r)} aria-label={`React ${r}`}>{r}</button>)}</div>{state.reactions?.[state.role === 'guide' ? 'runner' : 'guide'] && <span className="received-reaction">The other human sent {state.reactions[state.role === 'guide' ? 'runner' : 'guide']}</span>}</div><div className="draw-actions"><button className="primary" onClick={onAgain}>DRAW AGAIN</button><button className="text-button" onClick={save}>SAVE BOTH WORLDS</button><button className="text-button" onClick={onHome}>RETURN HOME</button></div></main>; }
  return <main className="draw-stage"><Atmosphere/><header><div className="wordmark">WITHOUT WORDS</div><div className="draw-status"><span className="live-dot"/> THE OTHER HUMAN IS DRAWING TOO</div></header><section className="draw-heading"><p className="eyebrow">SAME WORD · TWO WORLDS</p><h1>{state.topic}</h1><p>Draw what this means to you. Their world stays hidden.</p></section><div className="timer" aria-label={`${remaining} seconds remaining`}>{String(remaining).padStart(2, '0')}<small>SEC</small></div><div className="canvas-wrap"><canvas ref={canvasRef} width={900} height={600} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end} aria-label="Your private drawing canvas"/><div className="canvas-sheen"/></div><div className="draw-toolbar"><div className="tool-group" aria-label="Colors">{COLORS.map(c => <button key={c} className={`color-swatch ${color === c ? 'active' : ''}`} style={{ background: c }} onClick={() => setColor(c)} aria-label={`Use ${c} pen`} />)}</div><div className="tool-group" aria-label="Brush size">{SIZES.map(s => <button key={s} className={`size-choice ${size === s ? 'active' : ''}`} onClick={() => setSize(s)} aria-label={`Brush size ${s}`}> <i style={{ width: s, height: s }} /></button>)}</div><button className="tool-button" onClick={undo} disabled={!history.current.length}>UNDO</button><button className="tool-button" onClick={clear}>CLEAR</button><button className="primary submit-drawing" onClick={() => setConfirmSubmit(true)} disabled={submitted || remaining <= 0}>{submitted ? 'DRAWING SENT' : 'REVEAL WHEN READY'}</button></div><p className="draw-note">Your drawing is private until the timer ends or both people submit.</p>{confirmSubmit && <div className="submit-confirm" role="dialog" aria-modal="true"><div><p className="eyebrow">ONE LAST LOOK</p><h2>Reveal this drawing now?</h2><p>Your drawing will be sent and cannot be edited. It remains hidden until both drawings are ready or the timer ends.</p><button className="primary" onClick={submit}>SUBMIT DRAWING</button><button className="text-button" onClick={() => setConfirmSubmit(false)}>KEEP DRAWING</button></div></div>}</main>;
}
function Atmosphere() { return <div className="atmosphere" aria-hidden="true"><i/><i/><i/></div>; }
