import { useState } from 'react';
import type { MatchState, WorldRegion } from '@without-words/shared';

const regions: [WorldRegion, string][] = [['east-asia', 'EAST ASIA'], ['south-asia', 'SOUTH ASIA'], ['central-eurasia', 'CENTRAL EURASIA'], ['africa', 'AFRICA'], ['americas', 'AMERICAS']];
const info: Record<string, { title: string; place: string; rule: string; source: string }> = {
  'yut-nori': { title: 'YUT NORI', place: 'Korea · East Asia', rule: 'A simplified digital adaptation of a traditional Korean board game.', source: 'https://www.heritage.go.kr/' },
  'pachisi-duel': { title: 'PACHISI DUEL', place: 'India · South Asia', rule: 'A shortened two-player adaptation of Pachisi, a cross-and-circle game documented in India.', source: 'https://www.metmuseum.org/en/art/collection/search/822852' },
  'assyk-aim': { title: 'ASSYK AIM', place: 'Kazakhstan · Central Eurasia', rule: "A digital game inspired by Kazakhstan's traditional Assyk games.", source: 'https://ich.unesco.org/en/RL/kazakh-traditional-assyk-games-01086' },
  oware: { title: 'OWARE', place: 'Ghana · West Africa', rule: 'A simplified adaptation of Oware, one of the best-known games in the wider Mancala family.', source: 'https://www.britishmuseum.org/collection/object/E_Af1996-16-1-a-ai' },
  'loteria-duo': { title: 'LOTERÍA DUO', place: 'Mexico · Americas', rule: 'An original two-player picture-matching game inspired by Mexican Lotería.', source: 'https://learninglab.si.edu/collections/la-loter%C3%ADa-a-mexican-bingo-game/bDNuPbo5ATe3wfPx' },
};

export function WorldGame({ state, onVote, onReady, onAction, onAgain, onChoose }: { state: MatchState; onVote: (region: WorldRegion) => void; onReady: () => void; onAction: (action: string, value?: number) => void; onAgain: () => void; onChoose: () => void }) {
  const [picked, setPicked] = useState<WorldRegion>(); const stage = state.worldStage; const game = state.worldGame ? info[state.worldGame] : undefined; const data = state.worldData; const mine = state.role === 'guide' ? 0 : 1;
  if (stage === 'vote') return <main className="world-shell"><Atmosphere/><p className="eyebrow">PLAY ACROSS THE WORLD</p><h1>Where should we travel?</h1><p className="world-copy">Choose privately. The other human will choose too.</p><div className="region-grid">{regions.map(([id, label]) => <button key={id} className={picked === id ? 'region-choice picked' : 'region-choice'} disabled={state.worldVoted} onClick={() => { setPicked(id); onVote(id); }}><span>{label}</span><i>{picked === id ? '✓' : '·'}</i></button>)}</div><p className="world-status">{state.worldVoted ? 'YOUR CHOICE IS SEALED · WAITING FOR THE OTHER HUMAN' : 'ONE QUIET VOTE'}</p></main>;
  if (!game) return null;
  if (stage === 'reveal' || stage === 'ready') return <main className="world-shell world-reveal"><Atmosphere/><p className="eyebrow">THE WORLD CHOOSES</p><h1>{state.worldRegion?.replaceAll('-', ' ').toUpperCase()}</h1><div className="world-choices"><span>YOUR CHOICE<br/><b>{state.worldChoices?.[state.role === 'guide' ? 0 : 1]?.replaceAll('-', ' ').toUpperCase()}</b></span><span>THEIR CHOICE<br/><b>{state.worldChoices?.[state.role === 'guide' ? 1 : 0]?.replaceAll('-', ' ').toUpperCase()}</b></span></div><div className="world-game-card"><p className="eyebrow">{game.place}</p><h2>{game.title}</h2><p>{game.rule}</p><a href={game.source} target="_blank" rel="noreferrer">LEARN MORE ↗</a></div>{stage === 'ready' && <button className="primary" onClick={onReady}>{state.worldReady ? 'WAITING FOR THE OTHER HUMAN' : 'I AM READY'}</button>}</main>;
  if (stage === 'finished') return <main className="world-shell world-reveal"><Atmosphere/><p className="eyebrow">WORLD TOUR COMPLETE</p><h1>{state.worldWinner === 'draw' ? 'A SHARED MOMENT' : state.worldWinner === state.role ? 'YOUR WORLD WON' : 'THEIR WORLD WON'}</h1><div className="world-game-card"><p>{game.place}</p><h2>{game.title}</h2><p>Two strangers explored a game across distance.</p></div><button className="primary" onClick={onAgain}>TRAVEL AGAIN</button><button className="text-button" onClick={onChoose}>CHOOSE ANOTHER GAME</button></main>;
  const turn = data?.turn === state.role; return <main className="world-shell world-play"><Atmosphere/><p className="eyebrow">{game.place}</p><h1>{game.title}</h1><p className="world-copy">{turn ? 'Your turn · choose a move.' : 'Their turn · the result will appear together.'}</p><div className="world-board">{game.title === 'OWARE' ? <div className="oware-board">{data?.board.map((n, i) => <button key={i} disabled={!turn || i > 5 || !n} onClick={() => onAction('sow', i)}>{n}</button>)}</div> : game.title === 'LOTERÍA DUO' ? <div className="lot-card">{data?.board.map(n => <button key={n} className={data.shared.includes(n) ? 'marked' : ''} disabled={!turn || data.shared.includes(n)} onClick={() => onAction('card', n)}>CARD {n + 1}</button>)}</div> : <div className="world-score"><strong>{data?.scores[mine] ?? 0}</strong><span>points</span><div className="world-track"><i style={{ width: `${Math.min(100, ((data?.scores[mine] ?? 0) / (data?.goal || 2)) * 100)}%` }}/></div></div>}</div>{game.title === 'ASSYK AIM' ? <div className="action-row">{[1, 2, 3].map(n => <button disabled={!turn} onClick={() => onAction('aim', n)} key={n}>POWER {n}</button>)}</div> : game.title !== 'OWARE' && game.title !== 'LOTERÍA DUO' && <button className="primary" disabled={!turn} onClick={() => onAction('throw')}>THROW THE STICKS</button>}{data?.lastResult && <p className="world-status">{data.lastResult}</p>}</main>;
}
function Atmosphere() { return <div className="atmosphere" aria-hidden="true"><i/><i/><i/></div>; }
